FROM        ubuntu:22.04

ARG         DEBIAN_FRONTEND=noninteractive

# Set a default conf for apt-get install
RUN         echo 'apt::install-recommends "false";' > /etc/apt/apt.conf.d/no-install-recommends && \
            # Install a few required packages
            apt-get update -qq -y && \
            apt install -qq -y curl gnupg2 software-properties-common && \
            add-apt-repository ppa:ondrej/php --yes && \
            # Update, upgrade
            apt-get update -qq -y && \
            apt-get upgrade -qq -y && \
            # Packages
            apt-get install -qq -y \
                # Calling fpm locally
                libfcgi-bin \
                # Manipulate iptables rules (example: block smtps)
                iptables \
                # php8.2-cgi \
                # php8.2-dba \
                # php8.2-dev \
                # php8.2-enchant \
                # php8.2-phpdbg \
                # php8.2-pspell \
                # php8.2-recode \
                # php8.2-snmp \
                # php8.2-sybase \
                # php8.2-tidy \
                php8.2-apcu \
                php8.2-bcmath \
                php8.2-bz2 \
                php8.2-cli \
                php8.2-curl \
                php8.2-fpm \
                php8.2-gd \
                # php8.2-geoip \
                php8.2-gmp \
                php8.2-imagick \
                php8.2-imap \
                php8.2-interbase \
                php8.2-intl \
                # php8.2-json \
                php8.2-ldap \
                php8.2-mbstring \
                php8.2-mcrypt \
                php8.2-memcache \
                php8.2-memcached \
                php8.2-mongodb \
                php8.2-mysql \
                php8.2-odbc \
                php8.2-opcache \
                php8.2-pgsql \
                php8.2-readline \
                php8.2-redis \
                php8.2-soap \
                php8.2-sqlite3 \
                php8.2-ssh2 \
                php8.2-xdebug \
                php8.2-xhprof \
                php8.2-xml \
                php8.2-xmlrpc \
                php8.2-zip && \
            # Set a symlink to simplify the configuration, as we use a single php version
            ln -s /etc/php/8.2 /etc/php/current && \
            # Log to stdout
            sed -i 's/^error_log.*/error_log = \/proc\/self\/fd\/2/g' /etc/php/current/fpm/php-fpm.conf && \
            echo 'access.log = /proc/self/fd/2' >> /etc/php/current/fpm/php-fpm.conf && \
            # Create log dir
            mkdir /var/log/php && \
            # Clean
            apt-get autoremove -qq -y && \
            apt-get autoclean -qq && \
            apt-get clean -qq && \
            # Empty some directories from all files and hidden files
            rm -rf /build /tmp/* /usr/share/php/docs /usr/share/php/tests && \
            find /root /var/lib/apt/lists /usr/share/man /usr/share/doc /var/cache /var/log -type f -delete

COPY        files/common/php-cli.ini /etc/php/current/cli/conf.d/30-custom-php.ini
COPY        files/common/php-fpm.ini /etc/php/current/fpm/conf.d/30-custom-php.ini
COPY        files/common/www.conf    /etc/php/current/fpm/pool.d/

# For custom Configuration that comes from outside (via a docker compose mount)
RUN         mkdir /etc/php/current/fpm/user-conf.d && \
            echo "; Default empty file" > /etc/php/current/fpm/user-conf.d/example.conf && \
            # Create home for www-data
            mkdir /home/www-data && \
            chown www-data:www-data /home/www-data && \
            usermod -d /home/www-data www-data && \
            mkdir -p /run/php && \
            chown www-data:www-data /run/php

COPY        files/8.x/docker-entrypoint.sh /docker-entrypoint.sh
RUN         chmod +x /docker-entrypoint.sh

ENV         ENVIRONMENT dev
ENV         PHP_ENABLED_MODULES ""
ENV         FPM_UID 33
ENV         FPM_GID 33

EXPOSE      9000

# At the end as it changes everytime ;)
ARG         BUILD_DATE
ARG         DOCKER_TAG
ARG         VCS_REF
LABEL       maintainer="Emmanuel Dyan <emmanueldyan@gmail.com>" \
            org.label-schema.build-date=${BUILD_DATE} \
            org.label-schema.name=${DOCKER_TAG} \
            org.label-schema.description="Docker PHP Image based on Debian and including main modules" \
            org.label-schema.url="https://cloud.docker.com/u/edyan/repository/docker/edyan/php" \
            org.label-schema.vcs-url="https://github.com/edyan/docker-php" \
            org.label-schema.vcs-ref=${VCS_REF} \
            org.label-schema.schema-version="1.0" \
            org.label-schema.vendor="edyan" \
            org.label-schema.docker.cmd="docker run -d --rm ${DOCKER_TAG}"

ENTRYPOINT  ["/docker-entrypoint.sh"]

CMD         ["/usr/sbin/php-fpm8.2", "--allow-to-run-as-root", "-c", "/etc/php/current/fpm", "--nodaemonize"]
