---

name: Publish Docker images

on:
  push:
    branches: [master]

jobs:
  push_to_registries:
    name: Push Docker images to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and Test all images
        run: bash scripts/build_all.sh

      - name: Push all images to docker hub
        run: docker push edyan/php

      - name: Tag all images with ghcr.io
        run: |
          for version in $(ls -d Dockerfile-*|sed -e "s/Dockerfile-/$1/g"); do 
            docker tag edyan/php:$version ghcr.io/${{ github.repository }}:$version;
          done
          docker tag edyan/php:latest ghcr.io/${{ github.repository }}:latest

      - name: Push all images to ghcr
        run: docker push ghcr.io/${{ github.repository }}